# Generated by Django 5.1.6 on 2025-02-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='short_description',
            field=models.TextField(default=None),
        ),
    ]
