# Generated by Django 5.1.6 on 2025-02-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_task_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='short_description',
        ),
    ]
